name: Package and Release CogMo Toolkit

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  package:
    name: Build on ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            req_file: requirements_mac.txt
            artifact_name: CogMoToolkit-Mac
            python_version: '3.12'
          - os: windows-latest
            req_file: requirements_windows.txt
            artifact_name: CogMoToolkit-Windows
            python_version: '3.13'
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install Build Tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install "setuptools<71.0.0" wheel
          python -m pip install pip-tools pyinstaller

      - name: Prepare Requirements
        shell: bash
        run: |
          # If Windows, generate the file on the fly
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            pip-compile requirements.in -o requirements_windows.txt
          fi
          # Install the OS-specific file
          pip install -r ${{ matrix.req_file }}

      - name: PyInstaller Build
        run: |
          python -m PyInstaller CogMo.spec --clean

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/